{% set name = "rocm-opencl-driver" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/archive/roc-{{ version }}.tar.gz
  sha256: ee88993a616dd7776f07b14838cc59a4d4bc02f275bda75632fa7362e3f32f75
  patches:
    - compile_flags.diff 
    - link_libraries.diff

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - clangdev 9.*
    - llvmdev 9.*
    - lld 9.*
    - llvm

test:
  commands:
    - roc-cl -h

about:
  home: https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver
  license: MIT
  license_family: MIT
  license_file: License
  summary: 'ROCm OpenCL Compiler Tool Driver'

extra:
  recipe-maintainers:
    - isuruf
